name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm]  # 使用矩阵策略分别为 Windows 和 Linux 打包
        node-version: [18]

    steps:
      - name: 1.读取仓库
        uses: actions/checkout@v3

      - name: 2.准备node环境
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 3.安装依赖
        run: npm install

      - name: 4.删除自动下载的 fpm 并安装 ARM 版本
        if: matrix.os == 'ubuntu-24.04-arm'
        run: |
          sudo apt install ruby ruby-dev build-essential
          sudo gem install --no-document fpm

          #验证安装
          ruby --version
          gem --version
          fpm --version

      - name: 4.为 Linux 平台单独打包
        if: matrix.os == 'ubuntu-24.04-arm'
        run: |
          export USE_SYSTEM_FPM="true"
          npm run electron:linux-build --linux
        env:
          GH_TOKEN: ${{ secrets.SHKJ_DEMO_RELEASE_TOKEN }}

      - name: 5.创建Release草稿
        run: gh release create ${{ github.ref_name }} --draft
        env:
          GH_TOKEN: ${{ secrets.SHKJ_DEMO_RELEASE_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 1.读取仓库
        uses: actions/checkout@v3

      - name: 2.发布
        run: gh release edit ${{ github.ref_name }} --draft=false
        env:
          GH_TOKEN: ${{ secrets.SHKJ_DEMO_RELEASE_TOKEN }}
