name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # 使用矩阵策略分别为 Windows 和 Linux 打包
        node-version: [18]   # 使用较低版本的 Node.js

    steps:
      - name: 1.读取仓库
        uses: actions/checkout@v3

      - name: 2.准备node环境
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: 3.安装依赖
        run: |
          sudo apt-get update
          # 添加 Python 3.10 的 PPA
          sudo add-apt-repository ppa:deadsnakes/ppa -y
          sudo apt-get update
          # 安装 Python 3.10 及相关开发工具
          sudo apt-get install -y python3.10 python3.10-dev python3.10-venv python3-pip
          npm install --unsafe-perm=true --build-from-source

      - name: 4.为 Linux 平台单独打包
        if: matrix.os == 'ubuntu-latest'
        run: |
          export USE_SYSTEM_FPM="true"
          npm run electron:linux-build --linux
        env:
          GH_TOKEN: ${{ secrets.SHKJ_DEMO_RELEASE_TOKEN }}

      - name: 5.创建Release草稿
        run: gh release create ${{ github.ref_name }} --draft
        env:
          GH_TOKEN: ${{ secrets.SHKJ_DEMO_RELEASE_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 1.读取仓库
        uses: actions/checkout@v3

      - name: 2.发布
        run: gh release edit ${{ github.ref_name }} --draft=false
        env:
          GH_TOKEN: ${{ secrets.SHKJ_DEMO_RELEASE_TOKEN }}
